### ISSUE TITLE
[BUG] Circular import of 'types'

### ISSUE THREAD

**Issue by MichaelTMatthews** [EdanToledo/Stoix#35]
### Describe the bug
The `types.py` file e.g. in `ppo` interferes with the `types` module from the standard Python library in certain situations.

Running from the debugger result is the following stacktace:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site.py", line 636, in <module>
    main()
  File "/usr/lib/python3.10/site.py", line 622, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib/python3.10/site.py", line 349, in addusersitepackages
    addsitedir(user_site, known_paths)
  File "/usr/lib/python3.10/site.py", line 232, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/usr/lib/python3.10/site.py", line 202, in addpackage
    import traceback
  File "/usr/lib/python3.10/traceback.py", line 5, in <module>
    import linecache
  File "/usr/lib/python3.10/linecache.py", line 8, in <module>
    import functools
  File "/usr/lib/python3.10/functools.py", line 22, in <module>
    from types import GenericAlias
  File "/home/mikey/PycharmProjects/Stoix/stoix/systems/ppo/types.py", line 1, in <module>
    from typing import Dict
  File "/usr/lib/python3.10/typing.py", line 25, in <module>
    import contextlib
  File "/usr/lib/python3.10/contextlib.py", line 6, in <module>
    from functools import wraps
ImportError: cannot import name 'wraps' from partially initialized module 'functools' (most likely due to a circular import) (/usr/lib/python3.10/functools.py)
```

We can see that `functools` is confusing the default python library `types` with the stoix `types`, by trying to import `GenericAlias` from the stoix `types` file.

### To Reproduce
1.  Run `stoix/systems/ppo/ff_ppo.py` using the PyCharm debugger

### Context (Environment)
Same as https://github.com/EdanToledo/Stoix/issues/34

### Possible Solution
I think the only solution is to rename the `types.py` files to something else - I've come across a similar situation before (see https://stackoverflow.com/questions/69007748/fatal-python-error-init-import-size-failed-to-import-the-site-module-in-anacon/72678670#72678670)

**Comment by EdanToledo** [comment]
Thanks so much for bringing this up! I've seen this before as well but I wonder why this isn't happening to me? regardless i think its probably worthwhile changing the file name anyway to avoid this issue popping up here and there. I'll make a quick change and push it.

**Comment by EdanToledo** [comment]
I've just merged a fix that should solve this, let me know if it works for you.

**Comment by MichaelTMatthews** [comment]
Fixed, thanks again!
