### ISSUE TITLE
[BUG] Stoix install fails with python 3.12

### ISSUE THREAD

**Issue by smorad** [EdanToledo/Stoix#90]
### Describe the bug
Stoix fails to install in a clean conda environment
### To Reproduce
```
conda create -n stoix python
...
pip install -e .
```
Results in
```
...
Collecting arch==5.0.1 (from rliable->id-marl-eval@ git+https://github.com/instadeepai/marl-eval->Stoix==0.0.1)
  Using cached arch-5.0.1.tar.gz (937 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [35 lines of output]
      <string>:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      Compiling ./arch/univariate/recursions.pyx because it changed.
      Compiling ./arch/bootstrap/_samplers.pyx because it changed.
      [1/2] Cythonizing ./arch/bootstrap/_samplers.pyx
      [2/2] Cythonizing ./arch/univariate/recursions.pyx
      Traceback (most recent call last):
        File "/Users/smorad/miniforge3/envs/stoix/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/smorad/miniforge3/envs/stoix/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/smorad/miniforge3/envs/stoix/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/vb/d133zwt15qn51k8m9h7b_mgm0000gn/T/pip-build-env-dv0nlsmd/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/vb/d133zwt15qn51k8m9h7b_mgm0000gn/T/pip-build-env-dv0nlsmd/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/vb/d133zwt15qn51k8m9h7b_mgm0000gn/T/pip-build-env-dv0nlsmd/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/vb/d133zwt15qn51k8m9h7b_mgm0000gn/T/pip-build-env-dv0nlsmd/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 210, in <module>
        File "<string>", line 151, in run_setup
        File "/private/var/folders/vb/d133zwt15qn51k8m9h7b_mgm0000gn/T/pip-install-wm4lwdk0/arch_ecf8e1f1145d44bf9d790d077f996b93/versioneer.py", line 1518, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/private/var/folders/vb/d133zwt15qn51k8m9h7b_mgm0000gn/T/pip-install-wm4lwdk0/arch_ecf8e1f1145d44bf9d790d077f996b93/versioneer.py", line 1445, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/vb/d133zwt15qn51k8m9h7b_mgm0000gn/T/pip-install-wm4lwdk0/arch_ecf8e1f1145d44bf9d790d077f996b93/versioneer.py", line 340, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```
### Expected behavior
To not crash

### Context (Environment)
Stoix `master` (845e4f112abf93dd865e857565478fc4be9e369e)
Python 3.12.3

### Possible Solution
I could pin to 3.10, but it would be nice to use the latest python version

**Comment by EdanToledo** [comment]
Aah yeah, I'd like it to work with python 12 as well. I'll look into it right now.

**Comment by EdanToledo** [comment]
It should be fixed now. give it a try.
